[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geom2d"
version = "0.0.1"
requires-python = ">=3.11"
authors = [
	{name = 'Estrella Sicardi', email = 'esicardi@ucm.es'}
]
[tool.setuptools.packages.find]
exclude = ["tests*"]